apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/elastic/helm-charts
    chart: elasticsearch
    helm:
      values: |
        pushgateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
