apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 8.5.1
    helm:
      values: |
        pushgateway:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    cluster.initial_master_nodes:
      - control-plane
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
